### Register
POST http://localhost:5001/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "username": "testuser",
  "email": "testuser@example.com",
  "password": "password123"
}

### Login
POST http://localhost:5001/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}
