@email = test1@example.com
@password = password123

### Register
POST http://localhost:5000/registration
Content-Type: application/json

{
  "first_name": "Test",
  "last_name": "User",
  "email": "{{email}}",
  "password": "{{password}}"
}

### Login
# @name login
@authToken = {{login.response.body.data.token}}
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}


### Profile
GET http://localhost:5000/profile
Authorization: Bearer {{authToken}}

### Update Profile
PUT http://localhost:5000/profile/update
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "first_name": "Test",
  "last_name": "Update"
}

### Update Profile Image
PUT http://localhost:5000/profile/image
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="Ma'isy Yazid I 2.jpg"
Content-Type: image/jpeg

< ./Ma'isy Yazid I 2.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Banners
GET http://localhost:5000/banner

### Services
GET http://localhost:5000/services
Authorization: Bearer {{authToken}}

### Balance
GET http://localhost:5000/balance
Authorization: Bearer {{authToken}}

### Top Up Balance
POST http://localhost:5000/topup
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "top_up_amount": 10000
}

### Transaction
POST http://localhost:5000/transaction
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "service_code": "PULSA"
}


### Get History Transaction
GET http://localhost:5000/transaction/history?offset=0&limit=2
Authorization: Bearer {{authToken}}
